{% set version = "1.8.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dbitest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DBItest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DBItest/DBItest_{{ version }}.tar.gz
  sha256: b45f1bcf1af5fc76342535f963c8bdbd0398efa9d9b92f7b1d37e2a4134a476e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip             # [win]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - r-base
    - r-blob >=1.2.0
    - r-callr
    - r-dbi >=1.2.1
    - r-desc
    - r-hms >=0.5.0
    - r-lubridate
    - r-magrittr
    - r-nanoarrow
    - r-palmerpenguins
    - r-rlang >=0.2.0
    - r-testthat >=2.0.0
    - r-withr
  run:
    - r-base
    - r-blob >=1.2.0
    - r-callr
    - r-dbi >=1.2.1
    - r-desc
    - r-hms >=0.5.0
    - r-lubridate
    - r-magrittr
    - r-nanoarrow
    - r-palmerpenguins
    - r-rlang >=0.2.0
    - r-testthat >=2.0.0
    - r-withr

test:
  commands:
    - $R -e "library('DBItest')"           # [not win]
    - "\"%R%\" -e \"library('DBItest')\""  # [win]

about:
  home: https://dbitest.r-dbi.org
  dev_url: https://github.com/r-dbi/DBItest
  license: LGPL-2.1-or-later
  summary: A helper that tests DBI back ends for conformity to the interface.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
